/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EANDROIDGOOGLEPLAYBILLING_AUTODEFS_H
#define S3EANDROIDGOOGLEPLAYBILLING_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_ANDROIDGOOGLEPLAYBILLING_NAME "s3eAndroidGooglePlayBilling"
#define S3E_EXT_ANDROIDGOOGLEPLAYBILLING_HASH 0xe13464e5

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("s3eAndroidGooglePlayBilling", 9)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !S3EANDROIDGOOGLEPLAYBILLING_AUTODEFS_H */
